[package]
name = "gluesql-opfs-storage"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true
publish = false

[dependencies]
gluesql-core.workspace = true
gluesql-redb-storage.workspace = true
redb = "2.6"
wasm-bindgen = "0.2.100"
wasm-bindgen-futures = "0.4.29"
js-sys = "0.3"
web-sys = { version = "0.3.78", features = [
  "FileSystemDirectoryHandle",
  "FileSystemFileHandle",
  "FileSystemGetFileOptions",
  "FileSystemReadWriteOptions",
  "FileSystemSyncAccessHandle",
  "StorageManager",
  "WorkerGlobalScope",
  "WorkerNavigator",
] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom.workspace = true

[lints]
workspace = true
